### ISSUE TITLE
00 Intro/00 BoilerPlate/ Documentation and steps to reproduce

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/webpack-1.x-by-sample#18]
There are some issues I've encountered when making this sample:
- When creating the js file it is called `studens.js` but no name is specified when creating webpack conf file (`webpack.conf.js`) or HTML file (`index.html`).
- When running webpack from the command line it says 'command not found' because webpack is not specified in PATH (tested in a Linux box from scratch). The command is located under `node_modules/.bin/webpack`.
- Once running `webpack` from the command line inside `bundle.js` the `students.js` code  is not transpilled to ES5. Babel needs to load the es2015 preset using .babelrc or **query** in _webpack.conf.js_:
  <pre lang="javascript">
  ...
  loader: "babel-loader",
  query: {
  &nbsp;&nbsp;&nbsp;&nbsp;presets: ["es2015"]
  }
  ...
  </pre>
  - Even adding query to `webpack.conf.js` the code is not transpilled. The test pattern needs to change from `/\.es6$/` to `/\.js$/`:
    <pre lang="javascript">
    ...
    test: /.js$/,
    exclude: /node_modules/,
    ...
    </pre>
- (Optional) How does look like adding some `code` or some kind stylish to file names and packages? E.g:
  We will write es6 code but we need to transpile it to es5, in order to do that we will install `babel-core plus` `babe-preset-es2015` and save it as a dev dependency on the `package.json` that has been generated by the npm init command we have created.
  Now we are going to create a js file called `students.js` that will include ES6 syntax.

**Comment by brauliodiez** [comment]
Thanks Santi,

Goot catches, @datencia is working on this sample, some of them we detected in the call we had some days ago (failure from our side we should had created issues on that), but there are some other details you are mentioning, that we are missing. @datencia can you go through the bullet points mentioned by @crsanti. Thanks :-).

You can review the progress of that update in the pull request #17 

Totally agree on the optional point, this style helps when reading the doc, we can follow this proposal.

Thanks for your feedback, I'm going to open a new issue, assigning one of the samples readme to let jump on that.

**Comment by datencia** [comment]
hi!

I'm working on it right now. About the optional point that @crsanti mentioned, it's actually included in the pull request #17 .

Thanks for your feedback.

**Comment by brauliodiez** [comment]
Pull request #17 merged
