### ISSUE TITLE
00 Intro/04 Jquery/ Readme.md (english version)

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/webpack-1.x-by-sample#19]
Assigned to: @crsanti 

Steps to get started:
- Fork the project.
- Open a new branch (or work on your forked master)
- Try to reproduce the example following the instructins on the readme.md
- Enhance the documents and correct errors.
- Create a pull request from the forked project to the original one (master).

Give me a buzz if you have any question.

**Comment by crsanti** [comment]
Is this issue ready to close?

**Comment by brauliodiez** [comment]
You are right, thanks for pointing that out
