### ISSUE TITLE
Review  01 Styles/03 SASS/ (EN / + ES?)

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/webpack-1.x-by-sample#34]
I'll step into this sample If anybody has no objection, what do you think? :smile:

**Comment by brauliodiez** [comment]
@vicmator is working on the Spanish version of this case (you could work on the english version).

If you want to grab both ESP and EN you cold jump as well into 04 Handling Images.

Choose the one that you preffer, thanks a lot for you help.

**Comment by crsanti** [comment]
Oh! I'll take then the full review of 04 Handling Images. :+1:

**Comment by brauliodiez** [comment]
Great create an issue and indicaré in a comment that you are taking that case. Thanks

**Comment by crsanti** [comment]
Nice, i'll open an issue to indicar que i'm working on it :smile:

**Comment by brauliodiez** [comment]
01/03 Spanish ready and merged by @vicmator pending english version review

**Comment by crsanti** [comment]
Is this issue ready to close?
