### ISSUE TITLE
Review 01 Styles / 04 Handling Images (EN + ES) 

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/webpack-1.x-by-sample#35]
I'll be working on this review :+1: .

**Comment by brauliodiez** [comment]
Great job !! Do you want to jump in to case 00 Fx/00 Typescript (EN / ES) ?

**Comment by crsanti** [comment]
That would be great!! :+1:

**Comment by brauliodiez** [comment]
Great create issue and its.yours, many thanks
