### ISSUE TITLE
Review 02 Fx / 00 Typescript (EN / ES)

### ISSUE THREAD

**Issue by crsanti** [Lemoncode/webpack-1.x-by-sample#38]
I'll be working on this section. :+1:

**Comment by brauliodiez** [comment]
Great Stuff, 

One tip, next time you open a new branch whenever you commit just indicate in the commit the ID of the issue you are working on, e.g.

Working on issue #38

By doing that your branch will appear on the issue itself (this page that you are browsing), and it's easier to track.

Are you in the mood to jump on 02 Fx / 01 React (EN / ES)? If you want to, you are more than welcome on that case :)

Thanks, excellent work.
