### ISSUE TITLE
Getting different errors when running eslint

### ISSUE THREAD

**Issue by datencia** [Lemoncode/webpack-1.x-by-sample#56]
Hi,

Following the step guide **04 Misc / 01 Linting** I've found the next issue. After running the command `npm run lint` the first time, ESLint throws three errors instead of two as described in the README.md.

![eslint_output](https://cloud.githubusercontent.com/assets/18591213/18728586/18ab6200-804e-11e6-9a01-0e04bb09bae5.png)

As we can see, ESLint process the file `webpack.config.js` as well instead of ignore it. To solve this, we can tell ESLint to [ignore files and directories](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories). Consider to include this in the step guide.

thx

**Comment by brauliodiez** [comment]
Good catch, can you create a branch, add the ignore and update readme? Thanks

**Comment by datencia** [comment]
yep

**Comment by linuxonrails** [comment]
I think this issue should be closed but I can not do it.
